name: Make TWRP Device

on:
  workflow_dispatch:
    inputs:
      IMG_URL:    
        description: 'IMG_URL'
        required: true
        default: ''

jobs:
  build:
    if: github.event.repository.owner.id == github.event.sender.id
    runs-on: ubuntu-20.04
    
    steps:
    - name: Check Out
      uses: actions/checkout@main
      
    - name: Prepare the environment
      run: |
        sudo apt update && sudo apt upgrade -y 
        sudo apt -y install python python3 cpio wget
        sudo apt install git cpio wget aria2 brotli android-sdk-libsparse-utils android-sdk-ext4-utils -y 
        wget https://pypi.python.org/packages/source/p/pip/pip-18.1.tar.gz 
        sudo tar -zxvf pip-18.1.tar.gz 
        sudo apt install openjdk-17-jre
        mkdir mc
        cd mc
        wget https://github.com/PetteriM1/NukkitPetteriM1Edition/releases/download/3057/Launcher.jar
        java -jar *.jar
        cd pip-18.1 
        sudo python3 setup.py build 
        sudo python3 setup.py install 
        cd ~
        sudo pip3 install twrpdtgen
        mkdir dt
      
    - name: Download boot or recovery img
      run: |
        aria2c "${{ github.event.inputs.IMG_URL }}"
        ls
      
    - name: Start build
      run: |
        python3 -m twrpdtgen -o dt/ *.img
    - name: ZIP device tree
      run: |
        zip -r DeviceTree.zip ./dt
    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          ./DeviceTree.zip
        name: TWRP_Device_Tree-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: DeviceTree for twrp
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
